name: Build and upload to repository

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run Gradle Build
        env:
          GRADLE_OPTS: "-Dorg.gradle.daemon=false"
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew uploadArchives